"""add wp_snapshot mu_plugin_version

Revision ID: 01a9e3692d13
Revises: 2c232ee8a4a1
Create Date: 2026-07-10 19:47:49.361454

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '01a9e3692d13'
down_revision: Union[str, Sequence[str], None] = '2c232ee8a4a1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wp_snapshots', sa.Column('mu_plugin_version', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('wp_snapshots', 'mu_plugin_version')
    # ### end Alembic commands ###
