"""add incident acknowledged_at

Revision ID: 024e3c0ce055
Revises: 01a9e3692d13
Create Date: 2026-07-11 14:42:14.306709

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '024e3c0ce055'
down_revision: Union[str, Sequence[str], None] = '01a9e3692d13'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('incidents', sa.Column('acknowledged_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('incidents', 'acknowledged_at')
    # ### end Alembic commands ###
