"""add wpscan daily request budget

Revision ID: 2c232ee8a4a1
Revises: 3b3cd5f54d50
Create Date: 2026-07-10 17:48:01.148341

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2c232ee8a4a1'
down_revision: Union[str, Sequence[str], None] = '3b3cd5f54d50'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('global_config', sa.Column('wpscan_daily_limit', sa.Integer(), server_default='25', nullable=False))
    op.add_column('global_config', sa.Column('wpscan_requests_today', sa.Integer(), server_default='0', nullable=False))
    op.add_column('global_config', sa.Column('wpscan_requests_date', sa.String(length=10), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('global_config', 'wpscan_requests_date')
    op.drop_column('global_config', 'wpscan_requests_today')
    op.drop_column('global_config', 'wpscan_daily_limit')
    # ### end Alembic commands ###
