"""add site client_name

Revision ID: 3b3cd5f54d50
Revises: f03ae62020b5
Create Date: 2026-07-10 16:50:16.946537

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3b3cd5f54d50'
down_revision: Union[str, Sequence[str], None] = 'f03ae62020b5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sites', sa.Column('client_name', sa.String(length=255), nullable=True))
    op.create_index('ix_sites_client_name', 'sites', ['client_name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_sites_client_name', table_name='sites')
    op.drop_column('sites', 'client_name')
    # ### end Alembic commands ###
