"""initial schema

Revision ID: a07d4b037809
Revises: 
Create Date: 2026-07-10 01:10:59.121253

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a07d4b037809'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('global_config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('telegram_chat_id', sa.String(length=64), nullable=True),
    sa.Column('digest_hour', sa.Integer(), nullable=False),
    sa.Column('digest_timezone', sa.String(length=64), nullable=False),
    sa.Column('ssl_alert_days_json', sa.JSON(), nullable=False),
    sa.Column('domain_alert_days_json', sa.JSON(), nullable=False),
    sa.Column('panel_base_url', sa.String(length=255), nullable=False),
    sa.Column('wpscan_api_key', sa.String(length=255), nullable=True),
    sa.Column('gsb_api_key', sa.String(length=255), nullable=True),
    sa.Column('vt_api_key', sa.String(length=255), nullable=True),
    sa.Column('healthchecks_url', sa.String(length=1024), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('url', sa.String(length=1024), nullable=False),
    sa.Column('expected_domain', sa.String(length=255), nullable=False),
    sa.Column('type', sa.Enum('wordpress', 'laravel', 'nextjs', name='sitetype'), nullable=False),
    sa.Column('check_interval_seconds', sa.Integer(), nullable=False),
    sa.Column('expected_keyword', sa.String(length=255), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('mu_plugin_token', sa.String(length=255), nullable=True),
    sa.Column('health_endpoint_url', sa.String(length=1024), nullable=True),
    sa.Column('ssh_host', sa.String(length=255), nullable=True),
    sa.Column('ssh_user', sa.String(length=255), nullable=True),
    sa.Column('ssh_key_path', sa.String(length=1024), nullable=True),
    sa.Column('ssh_project_path', sa.String(length=1024), nullable=True),
    sa.Column('audit_fetch_url', sa.String(length=1024), nullable=True),
    sa.Column('audit_fetch_token', sa.String(length=255), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('suspicious_patterns',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pattern', sa.Text(), nullable=False),
    sa.Column('is_regex', sa.Boolean(), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('severity', sa.Enum('warning', 'critical', name='patternseverity'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('blacklist_statuses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('site_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('google_safe_browsing_flagged', sa.Boolean(), nullable=False),
    sa.Column('virustotal_flagged', sa.Boolean(), nullable=True),
    sa.Column('raw_json', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('check_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('site_id', sa.Integer(), nullable=False),
    sa.Column('check_type', sa.Enum('uptime', 'health', 'content', 'redirect', 'ssl', 'domain', 'wp_cve', 'new_admin', 'dependency_cve', 'blacklist', name='checktype'), nullable=False),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('status_code', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('error_message', sa.String(length=1024), nullable=True),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_check_results_site_timestamp', 'check_results', ['site_id', 'timestamp'], unique=False)
    op.create_table('dependency_audits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('site_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('tool', sa.String(length=20), nullable=False),
    sa.Column('raw_json', sa.JSON(), nullable=False),
    sa.Column('high_critical_count', sa.Integer(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('incidents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('site_id', sa.Integer(), nullable=False),
    sa.Column('check_type', sa.Enum('uptime', 'health', 'content', 'redirect', 'ssl', 'domain', 'wp_cve', 'new_admin', 'dependency_cve', 'blacklist', name='checktype'), nullable=False),
    sa.Column('severity', sa.Enum('warning', 'critical', name='severity'), nullable=False),
    sa.Column('opened_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cause', sa.Text(), nullable=False),
    sa.Column('detail_json', sa.JSON(), nullable=False),
    sa.Column('notified_open_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notified_close_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('silences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('site_id', sa.Integer(), nullable=False),
    sa.Column('until', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ssl_domain_statuses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('site_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('ssl_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ssl_valid', sa.Boolean(), nullable=False),
    sa.Column('ssl_error', sa.String(length=1024), nullable=True),
    sa.Column('domain_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('whois_error', sa.String(length=1024), nullable=True),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('wp_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('site_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('core_version', sa.String(length=50), nullable=True),
    sa.Column('core_update_available', sa.String(length=50), nullable=True),
    sa.Column('php_version', sa.String(length=50), nullable=True),
    sa.Column('plugins_json', sa.JSON(), nullable=False),
    sa.Column('themes_json', sa.JSON(), nullable=False),
    sa.Column('admin_usernames_json', sa.JSON(), nullable=False),
    sa.Column('raw_report_json', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('wp_snapshots')
    op.drop_table('ssl_domain_statuses')
    op.drop_table('silences')
    op.drop_table('incidents')
    op.drop_table('dependency_audits')
    op.drop_index('ix_check_results_site_timestamp', table_name='check_results')
    op.drop_table('check_results')
    op.drop_table('blacklist_statuses')
    op.drop_table('users')
    op.drop_table('suspicious_patterns')
    op.drop_table('sites')
    op.drop_table('global_config')
    # ### end Alembic commands ###
