"""add site monitoring_mode

Revision ID: dcc915527d9b
Revises: 732afc82d6d1
Create Date: 2026-07-10 15:47:24.853737

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dcc915527d9b'
down_revision: Union[str, Sequence[str], None] = '732afc82d6d1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sites', sa.Column('monitoring_mode', sa.Enum('full', 'basic', name='monitoringmode'), server_default='full', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sites', 'monitoring_mode')
    # ### end Alembic commands ###
