"""add trusted domains table

Revision ID: f03ae62020b5
Revises: dcc915527d9b
Create Date: 2026-07-10 16:25:37.249674

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f03ae62020b5'
down_revision: Union[str, Sequence[str], None] = 'dcc915527d9b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


trusted_domains_table = sa.table(
    "trusted_domains",
    sa.column("domain", sa.String),
    sa.column("description", sa.String),
    sa.column("enabled", sa.Boolean),
)

# These were previously a fixed, code-level allowlist (KNOWN_BENIGN_IFRAME_DOMAINS
# in app/checks/content_integrity.py) -- seeding them here preserves existing
# behavior now that the list is panel-editable instead of hardcoded.
DEFAULT_TRUSTED_DOMAINS = [
    ("googletagmanager.com", "Google Tag Manager"),
    ("google.com", "Google (Maps, reCAPTCHA, embeds)"),
    ("google.com.ar", "Google (country-code domain)"),
    ("youtube.com", "YouTube embeds"),
    ("youtube-nocookie.com", "YouTube privacy-enhanced embeds"),
    ("vimeo.com", "Vimeo embeds"),
    ("player.vimeo.com", "Vimeo player embeds"),
    ("maps.google.com", "Google Maps embeds"),
    ("recaptcha.google.com", "Google reCAPTCHA"),
    ("js.stripe.com", "Stripe payment widget"),
    ("paypal.com", "PayPal payment widget"),
    ("www.paypal.com", "PayPal payment widget"),
    ("facebook.com", "Facebook embeds/widgets"),
    ("www.facebook.com", "Facebook embeds/widgets"),
    ("instagram.com", "Instagram embeds"),
    ("open.spotify.com", "Spotify embeds"),
    ("calendly.com", "Calendly scheduling widget"),
    ("docs.google.com", "Google Docs/Forms embeds"),
    ("forms.gle", "Google Forms short links"),
]


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trusted_domains',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('domain', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('domain')
    )
    # ### end Alembic commands ###

    op.bulk_insert(
        trusted_domains_table,
        [{"domain": domain, "description": description, "enabled": True} for domain, description in DEFAULT_TRUSTED_DOMAINS],
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('trusted_domains')
    # ### end Alembic commands ###
